@TodoList.Doc415_HostAddress = https://localhost:7292

POST {{TodoList.Doc415_HostAddress}}/api/todo
Content-Type: application/json

{
  "Name" : "Serdar415",
  "IsCompleted" : false
}

###

POST {{TodoList.Doc415_HostAddress}}/api/todo
Content-Type: application/json

{
  //Todo
}

###

GET {{TodoList.Doc415_HostAddress}}/api/todo

###

DELETE {{TodoList.Doc415_HostAddress}}/api/todo/1

###

PUT {{TodoList.Doc415_HostAddress}}/api/todo/4
Content-Type: application/json

{
  "Name" : "Semra",
  "IsCompleted" : true

}

###

POST {{TodoList.Doc415_HostAddress}}/api/todo
Content-Type: application/json

{
  //Todo
}

###
